#!/bin/bash
# gqrx & fldigi Launcher
clear
echo "===== WMSI Startup script for HAB tracker station software ====="

# Useful coloring / styling commands (used as ${bold}**Text**${normal})
bold=$(tput bold)
normal=$(tput sgr0)

# Constants likely to be changed
rtty_freq="434.25 MHz"
sdr_device="Realtek RTL2838UHIDIR SN: 00000001"

# We use the snd-aloop module (equivalent to a driver in Windows)
# to handle the audio loopback, which feeds the radio sound output by gqrx 
# back into dl-fldigi for analysis. 
# This loopback method is much more reliable than the previous Pulse Audio-based method.

# Let's start by loading the kernel module:
echo "Bringing up ALSA audio loopback..."
sudo modprobe snd-aloop
sleep 2

clear


read -p "Press ENTER now to start gqrx..."
# Copy the good configuration:
cp ~/.config/gqrx/working1707261615.conf.BAK ~/.config/gqrx/default.conf
# Start gqrx:
./start_gqrx &>/dev/null &
sleep 2
read -p "Once you have finished setting up gqrx and started it, press ENTER here..."
read -p "Press ENTER again to confirm that gqrx is fully started 
 (you can see the ${bold}moving${normal} spectrum and waterfall)..."

clear

echo "====================================================================
You will now need to configure dl-fldigi to receive and decode
the audio from gqrx.

This involves:
    1. Making sure DL-FLDIGI is configured to receive RTTY 
       (see WMSI docs)
    2. Ensuring DL-FLDIGI is set to listen to the loopback device:
       (make sure ${bold}Configure->Sound Card->Devices->PortAudio->Capture${normal}
       is set to ${bold}'Loopback: PCM (hw:1,0)'${normal})
    3. Making sure it's tuned onto the two humps/yellow lines 
       and/or use autotune (enable 'RxID’; upper right).

====================================================================
"
read -p "Press ENTER now to start dl-fldigi..."

# Let's start fldigi now that gqrx is listening and playing back...
echo "Starting dl-fldigi..."
./start_dlfldigi &>/dev/null &
sleep 5
echo "Have fun tracking!"
echo "(close this terminal to close everything)"

# don't close unless all closed
wait
