#!/bin/bash
# gqrx & fldigi Launcher

BASEDIR=$(dirname "$(readlink -f "$0")")

clear
echo "===== WMSI Startup script for HAB tracker station software ====="

# Useful coloring / styling commands (used as ${bold}**Text**${normal})
bold=$(tput bold)
normal=$(tput sgr0)

# Constants 
rtty_freq="434.25 MHz"
sdr_device="Realtek RTL2838UHIDIR SN: 00000001"
DL_FLDIGI_ROOT=~/dl-fldigi/src
GQRX_ROOT=~/gqrx-2.6-rpi3-2

# We use the snd-aloop module (equivalent to a driver in Windows)
# to handle the audio loopback, which feeds the radio sound output by gqrx 
# back into dl-fldigi for analysis. 
# This loopback method is much more reliable than the previous Pulse Audio-based method.

# Let's start by loading the kernel module:
echo "Bringing up ALSA audio loopback..."
sudo modprobe snd-aloop
sleep 2

clear

echo "===============================================================
You will need to start up ${bold}two${normal} pieces of software.
The first tunes the radio and the second decodes the output.
These must be opened and setup ${bold}in sequence${normal} or they will crash.

This involves: 
    1. Pressing the ${bold}Play${normal} button to start reading input.
    2. Tuning to the peak near the frequency ${bold}$rtty_freq${normal}.
       You’re tuned when two ‘humps’ show up under the audio tab on the right.
       
Once gqrx is playing, return to this terminal and press ENTER.
===============================================================
"
read -p "Press ENTER now to start gqrx..."
# Copy the good configuration:
cp $BASEDIR/config/gqrx_default.conf ~/.config/gqrx/default.conf
# Start gqrx:
sh $GQRX_ROOT/run_gqrx.sh &>/dev/null &
sleep 2
read -p "Once you have finished starting gqrx, press ENTER here..."
read -p "Press ENTER again to confirm that gqrx is ${bold}fully${normal} started 
 (you can see the ${bold}moving${normal} spectrum and waterfall)..."

clear

echo "====================================================================
You will now need to configure dl-fldigi to receive and decode
the audio from the previous program, gqrx.

This involves:
    1. Enabling autotune to hold frequency (enable '${bold}RxID${normal}’; upper right)
    2. Tune it once by clicking between the ${bold}two humps/yellow lines${normal}

====================================================================
"
read -p "Press ENTER now to start dl-fldigi..."

# Let's start fldigi now that gqrx is listening and playing back...
echo "Starting dl-fldigi..."
# Copy the good configuration
cp $BASEDIR/config/dl-fldigi.prefs ~/.dl-fldigi/
cp $BASEDIR/config/fldigi_def.xml ~/.dl-fldigi/
# Start dl-fldigi
$DL_FLDIGI_ROOT/dl-fldigi --hab &>/dev/null &
sleep 5
echo "Have fun tracking!"
echo "(close this terminal to close everything)"

# don't close unless all closed
wait
